### ISSUE TITLE
Upgrade to WPILib 2019

### ISSUE THREAD

**Issue by kevinzwang** [DeepBlueRobotics/test-board#10]
The new WPILib extension is not compatible with projects built with the alpha version of the extension. I suggest you create a new project and copy the code we wrote to there, so it's compatible with the stable WPILib version.

**Comment by kevinzwang** [comment]
Although you might want to wait until CTRE publishes their 2019 libs

**Comment by brettle** [comment]
Also, according to the ChiefDelphi announcement, "Please note these won’t
be able to be used on a robot until kickoff, as the 2019 RoboRio image from
the NI 2019 update installer is required.
